---
  title: "Skin Metabolic Activity"
author: "Don R Schoolmaster Jr. and Jay T Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Set working directory
```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/skin")
```

# Load packages
```{r}
require("MASS")
require("psych")
```

# Read in data 
```{r}
ages.raw.count <- read.table("data/skin.age.counts.txt", sep = "\t", header = T)

# Remove subject "G1"
ages <- ages.raw.count[ ! ages.raw.count$subject == "G1", ]
```

# Create dummy variables for multinomial variables
```{r}
# Shower frequency
  # "1" = < three times per week
  # "2" = every other day
  # "3" = once per day
show.f2 <- ifelse(ages$show.freq==2,1,0)
show.f3 <- ifelse(ages$show.freq==3,1,0)

# Shower length
  # "1" = 0 - 5 mins
  # "2" = 5 - 15 mins
  # "3" = > 15 mins
show.l2 <- ifelse(ages$show.leng==2,1,0)
show.l3 <- ifelse(ages$show.leng==3,1,0)

# Last shower
  # "1" = > 48 hrs
  # "2" = 24 - 48 hrs
  # "3" = < 24 hrs
show.last2 <- ifelse(ages$last.show==2,1,0)
show.last3 <- ifelse(ages$last.show==3,1,0)

# Merge dummry variables into dataframe
ages.2 <- data.frame(ages[,c(1:6,11:16)], show.f2,show.f3,show.l2, 
          show.l3,show.last2,show.last3)

# Set up a design matrix that we might use later
X <- data.frame(ages.2[,-c(1,3:5)])

# Center age for later interpretation
cat("average age in survey is", round(mean(ages$age),1))
prop.act <- (ages$active/ages$total)
summary(f.act<-glm.nb(ages$active~.-total+offset(log(total)),data=X))
X$age <- X$age-mean(X$age)
age.match <- data.frame(ages$age, X$age)
age.fit <- lm(ages.age ~ X.age, data = age.match)
inter <- coef(age.fit)[1]  
```

# Post-hoc test to evaluate interaction between age and shower length
```{r}
fit <- lm(log(prop.act) ~ X$age + show.l2 + X$age*show.l2)
summary(fit)

# Multiple regression parameters
short.int <- fit$coefficients[1]
short.slp <- fit$coefficients[2]
long.int <- short.int + fit$coefficients[3]
long.slp <- fit$coefficients[2]
```

# Plotting log-transformed
```{r}
png(filename="figures/skin.age-log.png",
    width = 800, height = 800, res = 96*2)
plot.new()
par(mar = c(5, 6, 4, 2))

plot(X$age, prop.act, log = "y", ylim = c(0.001, 0.4), xlim = c(-45, 50), 
     xlab = expression(paste("Age")), cex.lab = 1.5,
     ylab = NA,
     xaxt = "n", yaxt = "n",
     pch = 22, lwd = 1.5, bg = "red", col = "black", cex = 2)
mtext("Proportion Active", side = 2, line = 4, cex = 1.5)
#axis(side=1, lwd.ticks = 2, cex.axis = 1, at = c(0, 20, 40, 60, 80), las=1) 
axis(side=1, lwd.ticks = 2, cex.axis = 1, las = 1, labels = c("0", "20",
              "40", "60", "80"), at = c(0 - inter, 20 - inter, 40 - inter, 
              60 - inter, 80 - inter))
#axis(side=3, lwd.ticks = 2, cex.axis = 1, at = c(0, 20, 40, 60, 80), labels = F)
axis(side=3, lwd.ticks = 2, cex.axis = 1, at = c(0 - inter, 20 - inter, 
              40 - inter, 60 - inter, 80 - inter), labels = F)
axis(side=2, lwd.ticks = 2, cex.axis = 1, at = c(0, 0.005, 0.05, 0.5), las=1)
axis(side=4, lwd.ticks = 2, cex.axis = 1, at = c(0, 0.005, 0.05, 0.5), labels = F)
box(lwd = 2)

# Add multiple regression lines

curve(exp(coef(fit)[1]) * exp(coef(fit)[2]*x), from = -40, to = 45, 
       ylim = c(0, 0.5), add = TRUE, lwd = 2, lty = 1)

curve(exp(coef(fit)[1] + coef(fit)[3]) * exp(coef(fit)[2]*x),
      from = -40, to = 45, ylim = c(0, 0.5), add = TRUE, lwd = 2, lty = 2)

legend(5, 0.003, legend = c("short shower", "long shower"), seg.len = 2.0,
       xjust = 1, lwd = 2, lty = c(1, 2), bty = 'n', cex = 0.85, y.intersp = 1.0)

# Close Plot Device
dev.off()
graphics.off()
```

# Plotting non-log-transformed
```{r}
png(filename="figures/skin.age.png",
    width = 800, height = 800, res = 96*2)
plot.new()
par(mar = c(5, 6, 4, 2))

plot(X$age, prop.act, ylim = c(-0.05, 0.4), xlim = c(-45, 50), 
     xlab = expression(paste("Age")), cex.lab = 1.5,
     ylab = NA,
     xaxt = "n", yaxt = "n",
     pch = 22, lwd = 1.5, bg = "red", col = "black", cex = 2)

mtext("Proportion Active", side = 2, line = 4, cex = 1.5)
axis(side=1, lwd.ticks = 2, cex.axis = 1.5, las = 1, labels = c("0", "20",
              "40", "60", "80"), at = c(0 - inter, 20 - inter, 40 - inter, 
              60 - inter, 80 - inter))
axis(side=3, lwd.ticks = 2, cex.axis = 1.5, at = c(0 - inter, 20 - inter, 
              40 - inter, 60 - inter, 80 - inter), labels = F)
axis(side = 2, lwd.ticks = 2, cex.axis = 1.5, las = 1,
    labels = c("0.0", "0.1", "0.2", "0.3", "0.4"), at = c(0, 0.1, 0.2, 0.3, 0.4))
axis(side=4, lwd.ticks = 2, cex.axis = 1, at = c(0, 0.10, 0.20, 0.30, 0.40), labels = F)
box(lwd = 2)

curve(exp(coef(f.act)[1]) * exp(coef(f.act)[2]*x), from = -40, to = 45, 
      ylim = c(0, 0.5), add = TRUE, lwd = 2, lty = 1)

curve(exp(coef(f.act)[1]) * exp(coef(f.act)[2]*x) *exp(coef(f.act)[11]), 
      from = -40, to = 45, add = TRUE, lwd = 2, lty = 2)

legend(45, 0.42, legend = c("short shower", "long shower"), seg.len = 2.0,
       xjust = 1, lwd = 2, lty = c(1, 2), cex = 0.85, bty = 'n', y.intersp = 1.0)

# Close Plot Device
dev.off()
graphics.off()
```

# Left over code for making regression and confidence intervals
```{r}
# Add regression line
newage <- seq(min(ages$age), max(ages$age), 1)
act.fit <- summary(f.act<-glm.nb(ages$active~.+offset(log(X$total)),data=X[,-2]))
regline <- predict(act.fit, newdata = data.frame(age = newage))
regline <- 10^(regline)
lines(newage, regline, lwd = 2)

# Add 95% confidence intervals
conf95 <- predict(fit, newdata = data.frame(age = newage),
                  interval = c("confidence"), level = 0.95, type = "response")
conf95 <- 10^(conf95)
matlines(newage, conf95[, c("lwr", "upr")], type="l", lty = 2, lwd = 2, col = "black")
```